export const dataSagaActions = {
  LOAD_LISTS: 'LOAD_LISTS',
  LOAD_TASKS: 'LOAD_TASKS',
  LOAD_COMMENTS: 'LOAD_COMMENTS', 
  ADD_LIST: 'ADD_LIST',
  ADD_TASK: 'ADD_TASK',
  ADD_COMMENT: 'ADD_COMMENT',  
  REMOVE_LIST: 'REMOVE_LIST',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_COMMENT: 'REMOVE_COMMENT', 
  UPDATE_LIST: 'UPDATE_LIST',
  UPDADE_TASK: 'UPDADE_TASK',
  UPDATE_COMMENT:'UPDATE_COMMENT',
};
