export const dataSagaActions = {
  LOAD_LISTS: 'LOAD_LISTS',
  LOAD_TASKS: 'LOAD_TASKS',
  LOAD_COMMENTS: 'LOAD_COMMENTS', 
  ADD_LIST: 'ADD_LIST',
  ADD_TASK: 'ADD_TASK',
  ADD_COMMENT: 'ADD_COMMENT',  
  REMOVE_LIST: 'REMOVE_LIST',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_COMMENT: 'REMOVE_COMMENT', 
  RENAME_LIST: 'RENAME_LIST',
  RENAME_TASK: 'RENAME_TASK',
  CHANGE_COMMENT: 'CHANGE_COMMENT',
  UPDADE_TASK: 'UPDADE_TASK'
};
